### ISSUE TITLE
project dead? django-changuito to the rescue

### ISSUE THREAD

**Issue by angvp** [bmentges/django-cart#10]
Seems that this project is sort of dead, several forks have been made .. even I started one https://github.com/angvp/django-changuito with some improvements I'd like to add some of my work there, but the process here seems to be slow, people who want to use a django-cart version with more features please give a try to django-changuito or let's make a deal with all the forks and make the next release of django-cart more complete and with more maintainers...

What do you think?

**Comment by bmentges** [comment]
I am in need of maintainers. Do you guys want to participate?

Thanks,
Bruno
