### ISSUE TITLE
Pypi package outdated

### ISSUE THREAD

**Issue by prodigel** [bmentges/django-cart#14]
Hello there,

Installing django-cart using pip I've noticed that the pypi repo has an outdated version: cart.py.clear method is broken there, while here (github) the issue is already fixed.
Would you mind pushing an updated version?

Many thanks!

**Comment by bmentges** [comment]
Done.

It's updated to 1.0.3. 

https://pypi.python.org/pypi/django-cart/1.0.3

Tell me if it's everything ok. Thanks.

**Comment by prodigel** [comment]
All good. Thanks for the quick action!

Best regards,
Florin.
