### ISSUE TITLE
update does nothing

### ISSUE THREAD

**Issue by tfyr** [bmentges/django-cart#15]
def update(self, product, quantity, unit_price=None):
        try:
            item = models.Item.objects.get(
                cart=self.cart,
                product=product,
            )
        except models.Item.DoesNotExist:
            raise ItemDoesNotExist

may be   
        else: #ItemAlreadyExists
            item.unit_price = unit_price
            item.quantity = int(quantity)
            item.save()

**Comment by bmentges** [comment]
Sorry for the long delay in answering.

So you are proposing that the update be changed into insert or update? Thats a good idea. Do you have a pull request with this change and its tests?

Thanks

**Comment by bmentges** [comment]
Fixed in PR #16
