### ISSUE TITLE
Model imports

### ISSUE THREAD

**Issue by josephmuli** [bmentges/django-cart#26]
Hey, you may have done a model import the wrong way in [cart.py](https://github.com/bmentges/django-cart/blob/master/cart/cart.py) , I'm using python3 and Django 1.9.7

**Comment by caroso1222** [comment]
You can try downloading the project and inserting it into your apps folder. Then change `import models` in cart.py for:

```python
try:
    import models
except:
    from . import models
```

**Comment by josephmuli** [comment]
aaaaah yes! awesome

**Comment by rightx2** [comment]
Do I have to do it manually? Why don't you make pull-request or something?

**Comment by caroso1222** [comment]
@rightx2 there is already an unmerged PR about this
