### ISSUE TITLE
Problem with Python 3.* & Django 2.*

### ISSUE THREAD

**Issue by adrien7sd** [bmentges/django-cart#33]
Hi 
Thank you for making this very useful and awesome library.
There are certain issues with this when we try to use it with python 3.* and django 2.*
We have found the fix for it, please apply these fixes so that we don't have to edit the two files everytime we install this.

    * Bug fix with the django cart package
    * Update file site-packages/cart/cart.py
    At line 2
    - *from . import models* in place of the import declaration.

and 

    *** Update file site-packages/cart/models.py
    At line 27
    replacement: cart = models.ForeignKey(Cart, verbose_name=_('cart'), on_delete=models.CASCADE)
    At line 31
    replacement: content_type = models.ForeignKey(ContentType,  on_delete=models.CASCADE)

**Comment by MeNsaaH** [comment]
The tests also should be executed on a CI. I can help with that. But to do that we need to create the `manage.py` file for tests @bmentges. The project a simple refactor to support the current django. I'm working on that. What do you think?
